# Generated by Django 4.2.2 on 2023-08-25 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_internship'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Internship',
        ),
    ]
